# Generated by Django 5.2.8 on 2025-11-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_horariodisponivel_agendamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='servicos',
            field=models.ManyToManyField(blank=True, related_name='profissionais', to='servicos.servico'),
        ),
    ]
